### ISSUE TITLE
Small pepper-poppers don't animate, animate on other target hits

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#133]
![screenshot from 2015-03-31 01 09 50](https://cloud.githubusercontent.com/assets/5543934/6910614/fc9dce6c-d744-11e4-8ca6-beea6451f5b2.png)

If i resize a pepper popper to a small size, I can shoot it (audio confirmation) but it does not animate.  I also noticed that shooting my plate rack caused a pepper popper to animate.  See the screenshot.  I shot the center rack target and it animated the pepper popper below it.  The same thing happened with the right rack target and the pepper popper below it.  Both of those make sound but do not animate when shot.  Only happened when I made them smaller

**Comment by phrack** [comment]
This is because of #105. There is an invisible target on the top "circle" of the popper that causes the animate to play. Hitting the popper anywhere but that "circle" causes a sound but no animation. Now, because of #105, when you scale the target the invisible target and what you see get all out of whack, thus shooting a seemingly random place can actually be a hit on where the invisible target is now.
